// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxqjuwofmzyprkzsebtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cWp1d29mbXp5cHJrenNlYnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDUyMTMsImV4cCI6MjA2MDAyMTIxM30.NrO_TzOdv5hgyqgVusmFZtY30SkHRyBFx_H-XzcCVVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);